### ISSUE TITLE
Multiple servers could call BeginPlay with authority on a singleton actor

### ISSUE THREAD

**Issue by improbable-valentyn** [spatialos/UnrealGDK#1019]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

## Description
For dynamic actors marked with `Singleton` (e.g. `GameState` or `GameMode`), `BeginPlay` may be called with authority on more than one server.

## Expected behavior
For all actors, `BeginPlay` should only be called with authority on one server. All other servers must call `BeginPlay` without authority.

## Current behavior
If the non-authoritative server checks out the singleton entity before triggering `BeginPlay`, it will call `BeginPlay` without authority (correct). If, however, it triggers `BeginPlay` before checking out that entity, it will call `BeginPlay` with authority.

## Environment
Windows 10
UnrealGDK `0.4.2`

## Internal ticket
UNR-1191

**Comment by ernopp** [comment]
Singletons have been removed
