### ISSUE TITLE
Workers will sometimes not gain authority when quickly reconnecting to an existing deployment

### ISSUE THREAD

**Issue by joshuahuburn** [spatialos/UnrealGDK#1199]
This results in a failure to spawn or simulate. When using the editor if you Play - Stop - Play in quick succession you can sometimes fail to launch correctly.

Fixed in `master` will be rolled out in 0.9.0 latest

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/1762
