### ISSUE TITLE
Initial dormant actors can't be immediately deleted

### ISSUE THREAD

**Issue by m-samiec** [spatialos/UnrealGDK#1224]
## Description
Actors which have their dormancy set to `DORM_Initial` won't be deleted on observing clients if they don't have their network relevancy flushed before being deleted.

## Expected behavior
Deletion of `DORM_Initial` Actors is always processed by clients.

## Possible solution
Don't use `DORM_Initial` or ensure that Actors have their network dormancy flushed before being deleted.

## Internal ticket
UNR-1797

**Comment by ernopp** [comment]
Resolved in 0.8.1 and onwards.

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/1747
