### ISSUE TITLE
Changing Spatial related configurations through the Unreal Editor can lead to issues if configuration files are not writable

### ISSUE THREAD

**Issue by ieva-improbable** [spatialos/UnrealGDK#1236]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).
-------

## Issue
Changing Spatial related configurations through the Unreal Editor can lead to problems if the configuration files are not writable. For instance, trying to amend the number of maximum allowed dynamic subobjects per actor will not succeed if `DefaultSpatialGDKSettings.ini` file is locked. Moreover, this operation will not be able to complete and will prevent the Unreal Editor from launching PIE sessions.

## Workaround
Make sure that all configuration files are writable.

## Internal Ticket
UNR-1809

**Comment by oblm** [comment]
We cannot fix this without heavily modifying UnrealEngine code, which we won't do, as we like to maintain as close-a-parity as reasonably possible.
