### ISSUE TITLE
Error when launching a cloud deployment when a Linux client isn't built.

### ISSUE THREAD

**Issue by girayozil** [spatialos/UnrealGDK#1242]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).
-------

## Issue
As of release 0.6.0, you may get the following type of error when running a cloud deployment:
```Could not download workers: could not download Artifact(UnrealSimulatedPlayer@Linux.zip) for Worker(SimulatedPlayerCoordinator); could not retrieve artifact information for UnrealSimulatedPlayer@Linux.zip: rpc error: code = NotFound desc = Artifact(UnrealSimulatedPlayer@Linux.zip) of Assembly(offloading_workflow) of Project(demo) doesn't exist.```

This happens because SpatialOS expects the worker package that corresponds to every worker config. In this case, Simulated Player binaries are missing.

## Workaround
We have two potential workarounds:
1) Build a Linux client and upload it as part of the assembly. See https://github.com/improbableio/UnrealEngine/blob/4.22-SpatialOSUnrealGDK-0.6.0-rc/Templates/TP_SpatialGDK/spatial-resources/BuildProject.bat for a reference script. This is the recommended approach.
2) Remove `spatial/workers/improbable/spatialos.SimulatedPlayerCoordinator.worker.json` and re-run `spatial build build-config` to remove the `SimulatedPlayerCoordinator` bridge config and descriptor from the assembly and re-upload. With this approach Simulated Players will not work.

## Internal Ticket
COMP-2137

**Comment by oblm** [comment]
I've closed this as it's labeled **won't fix**.
