### ISSUE TITLE
Possession of different Pawns can sometime fail

### ISSUE THREAD

**Issue by m-samiec** [spatialos/UnrealGDK#1265]
## Description
When a client switches pawn possession, server and/or client RPCs can get indefinitely queued, sometimes resulting in a client soft-lock.

## Internal ticket
UNR-1816

**Comment by ernopp** [comment]
Resolved in 0.8.1 and later.

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/1284
