### ISSUE TITLE
UnrealGDK/Setup.bat fail to download some dependencies.

### ISSUE THREAD

**Issue by GeorgeAth** [spatialos/UnrealGDK#1320]
## Description
Running the UnrealGDK/Setup.bat return the following errors:

Error 1:
...
Successfully retrieved package type 'worker_sdk' with name 'c-dynamic-x86_64-gcc_libstdcpp-linux' and version '13.8.1' to '...\UnrealGDK\SpatialGDK\Build\core_sdk\worker_sdk\c-dynamic-x86_64-gcc_libstdcpp-linux.zip'
Encountered an error during command execution.        ]  43% [0.7MiB/s]s]
    failed to download package.
    failed to retrieve worker package: rpc error: context deadline exceeded

Error 2:
...
Finished: Retrieve dependencies
Starting: Unpack dependencies
Expand-Archive : The path '...\UnrealGDK\SpatialGDK\Build\core_sdk\worker_sdk\c-static-fullylinked-arm-clang_libcpp-ios.zip' either does not exist or is not a valid file system path.
At line:1 char:1136
+ ... p" -Force;  Expand-Archive -Path "...\UnrealGDK\SpatialGDK\Build\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (...\UnrealG..._libcpp-ios.zip:String) [Expand-Archive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

OS : Windows 10
Unreal Engine Version : 4.22-SpatialOSUnrealGDK-release (21/08/19)
UnrealGDK : release (21/08/19)

**Comment by JohnsonJackblue** [comment]
You can resolve the Error 1 by modifying the Setup.bat with --grpc_client_connection_timeout_s flag

Example:
`spatial package retrieve worker_sdk c-dynamic-x86_64-gcc_libstdcpp-linux       %PINNED_CORE_SDK_VERSION%   "%CORE_SDK_DIR%\worker_sdk\c-dynamic-x86_64-gcc_libstdcpp-linux.zip" --grpc_client_connection_timeout_s 5m`

**Comment by GeorgeAth** [comment]
Error 1 : I try "--grpc_client_connection_timeout_s 5m" and it is ignored. After 60 second i get the same timeout error.

Error 2 : I guess this error is due to the partial downloaded file that cant be unzipped.

Also in the end the batch file keep saying "UnrealGDK build completed successfully!"
I guess the batch file is not detecting the errors here.

**Comment by AlexanderNorton** [comment]
They are both a result of the same issue.

Give the 'c-static-fullylinked-arm-clang_libcpp-ios.zip' more time to download instead, not 'c-dynamic-x86_64-gcc_libstdcpp-linux.zip' which is successfully downloaded.

So:
`    spatial package retrieve worker_sdk      c-static-fullylinked-arm-clang_libcpp-ios  %PINNED_CORE_SDK_VERSION%   "%CORE_SDK_DIR%\worker_sdk\c-static-fullylinked-arm-clang_libcpp-ios.zip" --grpc_client_connection_timeout_s 5m`

@JohnsonJackblue just misread the error but gave the right solution!
