### ISSUE TITLE
Public header has implicit private dependency.

### ISSUE THREAD

**Issue by JHuculak** [spatialos/UnrealGDK#1462]
https://github.com/spatialos/UnrealGDK/blob/bade5c74271efe5b3ad2dc49e8a285249c692d95/SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h#L79

`UnrealMetadata::GetNativeEntityClass` is public-facing but has an implicit dependency on non-public files due to the log line on 79. Because this function is also marked with `FORCEINLINE`, this causes linking errors when trying to use this header as a dependency in an external module since the linker can't resolve the definition of `LogSpatialClassInfoManager` (as the reference is no longer isolated to the dll but leaks across module boundaries).

**Comment by ernopp** [comment]
thanks for raising
will be handled through https://improbableio.atlassian.net/browse/UNR-2458
