### ISSUE TITLE
Manually creating UChannels is not supported

### ISSUE THREAD

**Issue by m-samiec** [spatialos/UnrealGDK#1468]
## Description
The UnrealGDK does not support user's manually creating UChannels directly on UNetConnections.

## Expected behavior
Manually calling _UNetConnection::CreateChannelByName_ will result in undefined behaviour.

## Possible solution
Leave creation of channels to the UNetDriver.

**Comment by oblm** [comment]
I've closed this as it's labeled **won't fix**.
