### ISSUE TITLE
Inaccurate/misleading info on the git page

### ISSUE THREAD

**Issue by mybadstudios** [spatialos/UnrealGDK#1645]
## Description
I was wondering how large this download was gonna be and based on the git page it sounded like 3 - 4Gb but in fact it is 15Gb. The placing of the size information in the description needs to be adjusted and possibly updated

## Expected behavior
When looking at the installation steps it gets to the point where it says "Run setup.bat. This will download binaries and dependencies. Currently the complete fork is about 3 to 4Gb". This lead me to believe that once I run setup.bat it would download 3 to 4Gb of content

## Current behavior
When I fork the project I download about 3 to 4Gb but when I run setup.bat it downloads an additional 11Gb which I was not aware of. 

## Possible solution
Fix 1. Move that "the fork size is 3 - 4Gb" bit to the step where you say "Download this fork" rather than having it at the step that says "Run setup.bat to download additional stuff"
Fix 2. During the "Run setup.bat" step, add a note that the extra stuff being downloaded is 11Gb in size

The only size information on the page is the 3 to 4Gb info but the actual total size of the downloads amount to 15Gb. If I had this information before hand I would have stuck with the Unity version instead so this is rather a big consideration to keep in mind for people like me with (for example) 50Gb per month metered connections ...

## Environment
What were you trying to accomplish?
Download your fork so I could try out your system

Please detail your OS and Unreal Engine versions.
Running Win10 64 bit. I downloaded the 4.24 GDK Merge branch

Provide a general summary of the issue in the title field above.
As explained above. The download size information is placed in a very ambiguous and misleading place giving a false sense of size that turned out to be more than 25% of my monthly data where I was expecting to use less than 10%.

**Comment by ernopp** [comment]
Hi @mybadstudios thanks for report and sorry to hear you were caught out by the large install size

We will add a note in the docs to give a heads up on this.
