### ISSUE TITLE
Component constraint is assigned to incorrect field (EntityIdConstraint)

### ISSUE THREAD

**Issue by Jacmob** [spatialos/UnrealGDK#1660]
https://github.com/spatialos/UnrealGDK/blob/5afe664032fce484364ee75703f5342ef0270e57/SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h#L327

**Comment by ernopp** [comment]
Thanks for raising this

Has now been resolved in master and will be out in our next release

https://github.com/spatialos/UnrealGDK/commit/c85c4a07a929915466c6f1415ecf018fa116ff4a#diff-681ffc0ee0453e292590ab2773abf90e
