### ISSUE TITLE
Editor opens installing iTunes Tutorial page when iTunes is installed (4.24 + 4.25)

### ISSUE THREAD

**Issue by joshuahuburn** [spatialos/UnrealGDK#2880]
## Description
When packaging an iOS project from Windows which has installed iTunes from [Apple's web site](https://www.apple.com/itunes), the editor will open [this page,](http://docs.unrealengine.com/latest/INT/Engine/Tutorial/Mobile/InstallingiTunesTutorial.InstallingiTunesTutorial/index.html) and cannot package the project successfully. 

This has been fixed in `4.26` but impacts `4.24` and `4.25`.

## Expected behavior
Page is not opened and project is packaged correctly on `4.24` and `4.25`.

## Current behavior
The editor will open  [this page,](http://docs.unrealengine.com/latest/INT/Engine/Tutorial/Mobile/InstallingiTunesTutorial.InstallingiTunesTutorial/index.html), and cannot package the project successfully. 

## Possible solution
This is fixed in `4.26`. We could backport Epic's [solution](https://github.com/EpicGames/UnrealEngine/commit/d7131f475c7cba134f391a08dabbcf1e336c1a75) to `4.24` and `4.25` if there is demand for this?

## Steps to reproduce
1. On Windows, install the iTunes from [Apple's web site](https://www.apple.com/itunes).
2. Try to package the iOS project follow this doc: [https://documentation.improbable.io/gdk-for-unreal/docs/launch-your-game-on-mobile-ios#step-2-set-up-your-development-machine|https://documentation.improbable.io/gdk-for-unreal/docs/launch-your-game-on-mobile-ios#step-2-set-up-your-development-machine].

## Internal ticket
[UNR-4856](https://improbableio.atlassian.net/browse/UNR-4856)

**Comment by oblm** [comment]
Unless customers ask for this, we won't fix it.
