### ISSUE TITLE
Setup.bat copying to wrong folder

### ISSUE THREAD

**Issue by ihavenick** [spatialos/UnrealGDK#491]
-------

## Description

Setup.bat copying to wrong folder.
It created folder in desktop but it must be on project folder.
 bug in setup.bat line 46  "..\..\..\spatial\schema"
I think it must be "..\..\spatial\schema"

## Expected behavior
Setup.bat to copy files to projectfolder/spatial

## Current behavior
Setup.bat copies files to upper folder /projectfolder/../

## Possible solution
change a single line

## Steps to reproduce

1. Run Setup.bat
2. get errors on run

## Environment
Windows 10 
UE 4.20

**Comment by improbable-valentyn** [comment]
Hi @ihavenick, I believe you may need to adjust your project structure as per our [porting guide](https://docs.improbable.io/unreal/alpha/content/get-started/porting-unreal-project-to-gdk#terms-used-in-this-guide).
Your new project structure should look something like this:
```
\OuterFolder\
\OuterFolder\spatial\schema
\OuterFolder\ProjectFolder\
```

In case it would be easier with a reference, please take a look at the project structure in our [ThirdPersonShooter](https://github.com/spatialos/UnrealGDKThirdPersonShooter/) project.

**Comment by ihavenick** [comment]
I used starter content allready. 

and realizied setup.bat is at wrong location or need to create a master folder for plugins.

![spatial](https://user-images.githubusercontent.com/4084471/47926072-bd94a780-ded0-11e8-9b8f-9be11596e6ba.png)

Leaving my wrong folder structure for others not to do like me.
