### ISSUE TITLE
Spatial UE4 4.21.1 fork doesn't contain a reference to a UnrealObjectRef.h

### ISSUE THREAD

**Issue by ohbeanz** [spatialos/UnrealGDK#551]
-------

## Description
4.21.1 branch of UE4 from spatial does NOT contain a referenced header file in the latest (master) branch of the Unreal GDK. Therefore, I cannot build my project from source. 

## Expected behavior
The file should be referenced in the 4.21.1 branch.

## Current behavior
Classes that include "UObject/improbable/UnrealObjectRef.h" cannot find the file specified and fails the build/compile.

## Possible solution
Include this file in the 4.21.1 spatial branch of UE4.

## Steps to reproduce
Provide an unambiguous set of steps to reproduce this bug. Include code snippets if relevant.

1. Download the UE4 spatial fork (4.21 branch: https://github.com/improbableio/UnrealEngine/tree/4.21) 
2. Download the Tutorial Starter Project (update to use 4.21 version of UE4)
3. Attempt to build Tutorial project using 4.21 fork.

## Environment
What were you trying to accomplish?
Building my project (which is currently using UE4 4.21.0

Please include your spatial diagnose output in full.

Please detail your OS and Unreal Engine versions.
Windows 10
UE4 4.21.1 (spatial fork)

Provide a general summary of the issue in the title field above.

**Temporary Workaround**: 
1. Create a new 'improbable' folder in the UE4 source directory (<UE4 Root>\Engine\Source\Runtime\CoreUObject\Public\Object)
2. Copy UnrealObjectRef.h file from 4.20 branch of UE4 into this folder (https://github.com/improbableio/UnrealEngine/blob/4.20-SpatialOSUnrealGDK/Engine/Source/Runtime/CoreUObject/Public/UObject/improbable/UnrealObjectRef.h)

**Comment by cyberbibby** [comment]
UnrealGDK currently only supports the modified version of SpatialOS for UE4.20.3. The 4.21 branch has not been ported yet.

**Comment by ohbeanz** [comment]
Right, figured. Thanks! Closing.
