### ISSUE TITLE
How to use proxy when I try setup SpatialGDK

### ISSUE THREAD

**Issue by shanyue1983** [spatialos/UnrealGDK#627]
-------

## Description
How to use proxy when I try build dependencies of SpatialGDK

## Steps to reproduce
Provide an unambiguous set of steps to reproduce this bug. Include code snippets if relevant.

1. double-click Setup.bat in the root directory of the Unreal GDK repository
2.Should I use proxy when I do that?
3.
4.

## Environment
What were you trying to accomplish?
I try build dependencies
So I double-click Setup.bat in the root directory of the Unreal GDK repository,

Please include your spatial diagnose output in full.
Starting: Setup.bat
Starting: Setup the git hooks
Finished: Setup the git hooks
Starting: Check dependencies
Finished: Check dependencies
Starting: Setup variables
Finished: Setup variables
Starting: Clean folders
Finished: Clean folders
Starting: Create folders
Finished: Create folders
Starting: Retrieve dependencies
Encountered an error during command execution.
    failed to download package.
    Cannot create connection to SpatialOS: context deadline exceeded
    context deadline exceeded

Please detail your OS and Unreal Engine versions.
win7 and UnrealEngine-4.20-SpatialOSUnrealGDK
Provide a general summary of the issue in the title field above.

**Comment by ernopp** [comment]
> Cannot create connection to SpatialOS: context deadline exceeded
> context deadline exceeded

This is an issue with the accessibility of SpatialOS in your environment. If this is still an issue for you environment, please could you post it on forums.improbable.io? (This forum is a better place for non-GDK related issues such as this one)

Many thanks

Many thanks
