### ISSUE TITLE
Failure to Build Multi-server Shooter Tutorial

### ISSUE THREAD

**Issue by music-coder** [spatialos/UnrealGDK#659]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

## Description
The Multiserver Tutorial is failing to build in Visual Studio or launch in the clones engine

## Expected behavior
The Tutorial should build without failure and be able to be launched

## Current behavior
Whenever I build the Multiserver Shooter Tutorial it always fails because it claims there is no directory such as WorkerSDK in the Unreal GDK that contains a schema. And sure enough I looked and couldn't find it either. It also gives me a Fatal error message when I try to open it with the cloned engine, saying that it is unable to read the module manifest from the UE4Engine.manifest

## Possible solution
This is not obligatory but if you have a preference, please suggest a fix for the bug.

## Steps to reproduce
Provide an unambiguous set of steps to reproduce this bug. Include code snippets if relevant.

Follow the Multiserver Shooter Tutorial until the point of building the project

## Environment
What were you trying to accomplish?

I am trying to setup the tutorial to get started with Spatial in Unreal. I am using Unreal 4.21, and Spatial 13.2

**Comment by ernopp** [comment]
Thank you for raising
This should be resolved since 0.6.2
