### ISSUE TITLE
4.21 NetDriver::RemoveClientConnection error

### ISSUE THREAD

**Issue by GeorgeR** [spatialos/UnrealGDK#765]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

## Description
Note that this is specific to 4.21, which introduces MappedClientConnections in NetDriver. This is unaccounted for in the current SpatialOS release in it's SpatialNetDriver so it's failing when trying to remove the address from MappedClientConnections.

## Expected behavior
The address should be added and removed from MappedClientConnections.

## Current behavior
Failure at RemoveClientConnection (as the address was never added in SpatialNetDriver).

## Possible solution
Wrap the calls like so:
```cpp
#if ENGINE_MINOR_VERSION >= 21
// 4.21+ stuff here
#endif
```

## Steps to reproduce
Regular join and quit loop in the shooter example using my 4.21 spatial release engine branch.

## Environment
Obviously not a high priority until/if you move to 4.21 but would appreciate some guidance.

**Comment by m-samiec** [comment]
This is resolved in our 4.22 release. Please let us know if we can provide more info.
