### ISSUE TITLE
Generating schema for UClasses that are not explicitly loaded/referenced by the currently loaded level is not supported

### ISSUE THREAD

**Issue by ernopp** [spatialos/UnrealGDK#861]
**Issue**

Generating schema for UClasses that are not explicitly loaded/referenced by the currently loaded level is not supported. For example, a hard coded path loaded at run-time will not be detected by the schema generator.

**Workaround**

Reference the class explicitly from an already loaded class (Level blueprint, GameMode etc). Alternatively, you can open the Blueprints for soft references before generating schema so that they are loaded into memory.

**Internal ticket**

NA

**Comment by mattyoung-improbable** [comment]
Fixed in 0.4.0
