### ISSUE TITLE
When launching a client from a cloud deployment, the Launcher chooses the first `.exe` file in alphabetical order

### ISSUE THREAD

**Issue by ernopp** [spatialos/UnrealGDK#862]
**Issue**

When launching a client from a cloud deployment, it chooses the first `.exe` file in alphabetical order, rather than selecting a particular one.

**Workaround**

When building your client, an underscore is added to the correct executable name.

**Internal Ticket**

LAUNCH-341

**Comment by mattyoung-improbable** [comment]
Fixed: GDK works around this issue.
