### ISSUE TITLE
Opening the Editor while you are uploading or launching a cloud deployment disables the GDK Toolbar Start button, and Selecting Stop on the GDK Toolbar stops the running cloud deployment.

### ISSUE THREAD

**Issue by ernopp** [spatialos/UnrealGDK#863]
**Issue**

Opening the Editor while you are uploading or launching a cloud deployment disables the GDK Toolbar Start button, and Selecting Stop on the GDK Toolbar stops the running cloud deployment.

**Workaround**

Wait for the cloud launch to finish, or launch the cloud deployment whilst the Editor is already open.

**Internal Ticket**

UNR-1006

**Comment by joshuahuburn** [comment]
This is now fixed as of 0.6.0
