### ISSUE TITLE
Schema generation removes non-alphanumeric characters.

### ISSUE THREAD

**Issue by m-samiec** [spatialos/UnrealGDK#885]
**Issue**

Schema generation removes non-alphanumeric characters. This can lead to name collisions in subobjects, properties, and RPCs, which is not supported and will result in an error.  

**Workaround**

Ensure that names are not identical with non-alphanumeric characters removed. For example, `My Property` and `MyProperty` will result in an error, but `My Property` and `MyProperty2` will not.

**Internal ticket**
[UNR-1322](https://improbableio.atlassian.net/browse/UNR-1322).

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/609

**Comment by oblm** [comment]
We now handle this use case.
