### ISSUE TITLE
BeginPlay() not being called on all WorldSettings actors

### ISSUE THREAD

**Issue by ieva-improbable** [spatialos/UnrealGDK#937]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

## Description
Currently on server worker BeginPlay() gets called only on WorldSettings actor for the persistent level, but not on WorldSettings actors for any of the streamed levels.

## Expected behavior
For native Unreal on server BeginPlay() gets called on WorldSettings actor for the persistent level as well as each of the streamed levels.

## Internal ticket
UNR-1408

**Comment by m-samiec** [comment]
https://github.com/spatialos/UnrealGDK/pull/2945
