### ISSUE TITLE
Client connections will be closed by the ServerWorker when using Blueprint or C++ breakpoints during play-in-editor sessions due to connection heartbeating

### ISSUE THREAD

**Issue by padhansell** [spatialos/UnrealGDK#940]
**Issue**

Client connections will be closed by the ServerWorker when using Blueprint or C++ breakpoints during play-in-editor sessions due to connection heartbeating. This will cause all entities related to the player to be deleted, such as Character, PlayerController and PlayerState.

**Workaround**

When debugging locally, increase the value of the HeartbeatTimeout setting (which can be found in the "Runtime Settings" menu) to a large value. Note that this value should be set back the default for regular non-Editor testing.

This value defines the number of seconds that a ServerWorker will wait to receive a heartbeat message from the client before considering it to be unresponsive and destroying it's connection. 

**Internal ticket**

UNR-1411

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/1643
