### ISSUE TITLE
Clients that connect after a Startup Actor (with bNetLoadOnClient = true) will not delete the Actor

### ISSUE THREAD

**Issue by m-samiec** [spatialos/UnrealGDK#941]
## Description
Clients that connect to a deployment after a Startup Actor has been deleted will miss the delete entity operation, so the Actor will persist locally.

## Workaround
Set bNetLoadOnClient to false on level actors that might get deleted.

## Tracking issue
UNR-1128

**Comment by ernopp** [comment]
Resolved in 0.8.1 and later.

**Comment by oblm** [comment]
This was fixed by: https://github.com/spatialos/UnrealGDK/pull/1357
