### ISSUE TITLE
Generating schema while asset manager is asynchronously loading causes editor to crash

### ISSUE THREAD

**Issue by mattyoung-improbable** [spatialos/UnrealGDK#944]
## Description
Running Generate Schema (full or incremental) can crash the editor if assets are being asynchronously loaded via the Asset Manager.

## Workaround
Wait for the Asset Manager to finish any async loading tasks before generating schema

## Tracking issue
UNR-1410

**Comment by oblm** [comment]
I've closed this as it's labeled **won't fix**.
