### ISSUE TITLE
Development and Shipping builds are incompatible

### ISSUE THREAD

**Issue by improbable-valentyn** [spatialos/UnrealGDK#951]
## Description
Development/Debug servers are incompatible with Test/Shipping clients and vice versa.

## Workaround
For deployments running with Development or Debug servers, use Development or Debug clients, and for deployments with Test or Shipping servers, use Test or Shipping clients.

## Tracking issue
UNR-1368

**Comment by oblm** [comment]
Fixed in: https://github.com/spatialos/UnrealGDK/pull/921

**Comment by m-samiec** [comment]
This has now be rolled out to release.
