### ISSUE TITLE
Some replication conditions do not always match native behaviour.

### ISSUE THREAD

**Issue by oblm** [spatialos/UnrealGDK#953]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

## Description
Some replication conditions do not always match native behaviour.

## Expected behavior
All replication conditions should match native Unreal.

## Current behavior
Some replication conditions do not match native Unreal. Some examples include:
- [`SimulatedOnly` + `SimulatedOrPhysics`] Initial value of property replicated with condition `SimulatedOnly` or `SimulatedOrPhysics` is being applied on clients with `Role != SimulatedProxy`.
- [`InitialOrOwner`] Non-Initial updates of property replicated with condition `InitialOrOwner` is being applied on non-owning clients.
- [`AutonomousOnly`] Initial updates of properties replicated with condition `AutonomousOnly` are flaky (there is a low chance of receiving the initial update, the following updates work fine)

## Environment
Windows 10
UnrealGDK `0.4.2`

## Internal ticket
UNR-1423

**Comment by m-samiec** [comment]
This issue is out-of-date and no longer fully relevant. Closed and new known issues made
https://github.com/spatialos/UnrealGDK/issues/2952
https://github.com/spatialos/UnrealGDK/issues/2983
